// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "doc",
      label: "Preface",
      id: "preface",
    },
    {
      type: "category",
      label: "Getting Started",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Getting Started",
        slug: "/getting-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "Optional Features",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Optional Features",
        slug: "/optional-features",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "optional-features",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Guides",
        slug: "/guides",
      },
      items: [
        {
          type: "doc",
          label: "Connecting to your database",
          id: "guides/tableplus",
        },
        {
          type: "doc",
          label: "Setting up your staging environment",
          id: "guides/staging",
        },
        {
          type: "doc",
          label: "Migrate from Vercel to AWS",
          id: "guides/migrate-vercel-to-aws",
        },
        {
          type: "doc",
          label: "Deploying to a Physical Server or Virtual Private Server",
          id: "guides/on-prem",
        },
      ],
    },
    {
      type: "category",
      label: "Concepts",
      collapsed: false,
      link: {
        type: "generated-index",
        title: "Concepts",
        slug: "concepts",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "concepts",
        },
      ],
    },
  ],
};

module.exports = sidebars;
