// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docSidebar: [
    {
      type: "category",
      label: "Getting Started",
      link: {
        type: "generated-index",
        title: "Getting Started",
        slug: "/getting-started",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "getting-started",
        },
      ],
    },
    {
      type: "category",
      label: "Guides",
      link: {
        type: "generated-index",
        title: "Guides",
        slug: "/guides",
      },
      items: [
        {
          type: "category",
          label: "Adding a new feature",
          items: [{ type: "autogenerated", dirName: "guides/replies" }],
        },
        {
          type: "doc",
          label: "Connecting to CockroachDB",
          id: "guides/tableplus",
        }
      ],
    },
  ],
};

module.exports = sidebars;
